# Generated by Django 2.2.1 on 2019-05-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0002_intervento'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventoAllegato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='interventiAllegati/%Y/%m/%d/')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('intervento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='interventi.Intervento')),
            ],
            options={
                'verbose_name_plural': 'InterventiAllegati',
            },
        ),
    ]
