# Generated by Django 2.2.1 on 2019-05-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0003_interventoallegato'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatoInterventoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=250)),
                ('ordine', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'StatiInterventoCliente',
            },
        ),
        migrations.CreateModel(
            name='StatoInterventoInterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=250)),
                ('ordine', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'StatiInterventoInterno',
            },
        ),
    ]
