# Generated by Django 2.2.1 on 2019-05-30 13:41

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias

    stato_intervento_cliente_model = apps.get_model(
        'interventi', 'StatoInterventoCliente'
    )
    stato_intervento_cliente_model.objects.using(db_alias).bulk_create([
        stato_intervento_cliente_model(
            descrizione='Nuovo',
            ordine=10,
        ),
        stato_intervento_cliente_model(
            descrizione='In carico',
            ordine=20,
        ),
        stato_intervento_cliente_model(
            descrizione='Completato',
            ordine=30,
        ),
    ])

    stato_intervento_interno_model = apps.get_model(
        'interventi', 'StatoInterventoInterno'
    )
    stato_intervento_interno_model.objects.using(db_alias).bulk_create([
        stato_intervento_interno_model(
            descrizione='Nuovo',
            ordine=10,
        ),
        stato_intervento_interno_model(
            descrizione='In attesa di preventivo',
            ordine=20,
        ),
        stato_intervento_interno_model(
            descrizione='Ordine materiale',
            ordine=30,
        ),
        stato_intervento_interno_model(
            descrizione='In attesa disponibilità fornitore',
            ordine=40,
        ),
    ])


def reverse_func(apps, schema_editor):
    stato_intervento_cliente_model = apps.get_model(
        'interventi', 'StatoInterventoCliente'
    )
    stato_intervento_interno_model = apps.get_model(
        'interventi', 'StatoInterventoInterno'
    )
    db_alias = schema_editor.connection.alias

    stato_intervento_cliente_model.objects.using(db_alias).all().delete()
    stato_intervento_interno_model.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0004_statointerventocliente_statointerventointerno'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
