# Generated by Django 2.2.1 on 2019-05-30 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0005_statointervento_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervento',
            name='stato_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interventi', to='interventi.StatoInterventoCliente'),
        ),
        migrations.AddField(
            model_name='intervento',
            name='stato_interno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interventi', to='interventi.StatoInterventoInterno'),
        ),
    ]
