# Generated by Django 2.2.1 on 2019-06-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0008_preventivo_preventivoallegato'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIntervento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=250)),
                ('ordine', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'TipiIntervento',
            },
        ),
    ]
