# Generated by Django 2.2.1 on 2019-06-03 19:15

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias

    tipo_intervento_model = apps.get_model(
        'interventi', 'TipoIntervento'
    )
    tipo_intervento_model.objects.using(db_alias).bulk_create([
        tipo_intervento_model(
            pk=1,
            descrizione='Manutenzione',
            ordine=10,
        ),
        tipo_intervento_model(
            pk=2,
            descrizione='Richiesta attrezzatura',
            ordine=20,
        ),
    ])


def reverse_func(apps, schema_editor):
    tipo_intervento_model = apps.get_model(
        'interventi', 'TipoIntervento'
    )
    db_alias = schema_editor.connection.alias

    tipo_intervento_model.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0009_tipointervento'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
