# Generated by Django 2.2.1 on 2019-06-03 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0010_tipointervento_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervento',
            name='tipo_intervento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interventi', to='interventi.TipoIntervento'),
        ),
    ]
