# Generated by Django 2.2.1 on 2019-06-03 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interventi', '0012_puntovendita_regione'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventoCommento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('intervento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='interventi.Intervento')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'InterventiCommenti',
            },
        ),
    ]
