# Generated by Django 2.2.1 on 2019-06-06 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0013_interventocommento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scadenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scadenza', models.DateField()),
                ('data_promemoria', models.DateField()),
                ('descrizione', models.CharField(max_length=250)),
                ('gestita', models.BooleanField()),
                ('annotazioni', models.TextField(blank=True)),
                ('fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scadenze', to='interventi.Fornitore')),
                ('punto_vendita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scadenze', to='interventi.PuntoVendita')),
            ],
            options={
                'verbose_name_plural': 'Scadenze',
            },
        ),
        migrations.CreateModel(
            name='ScadenzaAllegato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='scadenze/%Y/%m/%d/')),
                ('scadenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='interventi.Scadenza')),
            ],
            options={
                'verbose_name_plural': 'ScadenzeAllegati',
            },
        ),
    ]
